### ISSUE TITLE
Collapsible Sidebar

### ISSUE THREAD

**Issue by dbettin** [cristijora/vue-light-bootstrap-dashboard#2]
Thanks for this great design!

Is it possible to collapse and uncollapse the sidebar?

**Comment by cristijora** [comment]
@dbettin If you want to simply show hide it, you can use a css class and add it conditionally.

```css
.sidebar.sidebar-collapased {
  display: none;
}

.sidebar-collapsed
```
